# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoioeSq6WD8a44mj1QX4QTWZVgOAAHs_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Salary_Data.csv')

dataset

dataset_ndarray = dataset.values

dataset_ndarray

dataset_ndarray.shape

X = dataset_ndarray[:, :-1]
y = dataset_ndarray[:, -1]

print(X.shape, y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

from sklearn.linear_model import LinearRegression

salary_pred_LR = LinearRegression()

salary_pred_LR.fit(X_train, y_train)

y_pred = salary_pred_LR.predict(X_test)

print(y_pred)
print(y_test)

X_sample = np.array([[0], [12]])
y_pred_sample = salary_pred_LR.predict(X_sample)

plt.scatter(X_train, y_train, label='training data')
plt.scatter(X_test, y_test, label='test data')
plt.legend()

X_sample = np.array([[0], [12]])
y_pred_sample = salary_pred_LR.predict(X_sample)

plt.plot(X_sample, y_pred_sample, color='red', label='linear regression')
plt.legend()
plt.xlabel('Years Experienced')
plt.ylabel('Salary')
plt.title('Linear regression model')