# -*- coding: utf-8 -*-
"""Linear_regression_startups.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVdIVpCxvB1K5hihF3PqKaNC4XBsEfNe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('50_Startups.csv')
dataset

dataset_ndarray = dataset.values
dataset_ndarray

print(type(dataset))
print(type(dataset_ndarray))

dataset_ndarray.shape

X = dataset_ndarray[:, :3]
y = dataset_ndarray[:, -1]

dataset

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

from sklearn.linear_model import LinearRegression

pred_profit_LR = LinearRegression()

pred_profit_LR.fit(X_train, y_train)

# 150000, 100000, 300000
pred_profit_LR.predict([[150000, 100000, 300000]])

y_pred = pred_profit_LR.predict(X_test)

print(y_pred)
print(y_test)

y_test.shape

plt.plot(y_test, marker='o', markersize=10, label='actual value', linestyle='--', linewidth=0.5, color='green')
plt.plot(y_pred, marker='s', markersize=10, label='prediction', linestyle=':', linewidth=0.5, color='red')
plt.legend()
plt.grid()
plt.ylabel('Salary', color='orange', fontsize=20)
plt.title('regression result', color='green', fontsize=20)

plt.plot(np.abs(y_test-y_pred), marker='o', markersize=10, label='absolute error(test data)', linestyle='--', linewidth=0.5, color='green')
plt.grid()
plt.title('Absolute Error')
plt.legend()

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print('mse:', mse)
print('mae:', mae)
print('r2:', r2)

np.sqrt(mse)

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('rmse:', rmse)