# -*- coding: utf-8 -*-
"""Logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU2UXd5jZFciYchGHpONi1utNTn7p5ZC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('data_banknote_authentication.csv')
dataset

ndarray_dataset = dataset.values
ndarray_dataset

dataset.head(3)

X = ndarray_dataset[:, :-1]
 y = ndarray_dataset[:, -1]

print(X.shape, y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(X_train.shape, y_train.shape)

print(X_test.shape, y_test.shape)

from sklearn.linear_model import LogisticRegression

logisticR = LogisticRegression()
logisticR.fit(X_train, y_train)

y_pred = logisticR.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

# [[TN, FP],
#  [FN, TP]]

TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]

accuracy = (TP+TN) / (TP+TN+FP+FN)
error_rate = (FP+FN) / (TP+TN+FP+FN)

print(accuracy*100)
print(error_rate*100)

acc = accuracy_score(y_test, y_pred)
err = 1-acc

print(acc*100)
print(err*100)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)